[package]
name = "lowkey"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.86"
reqwest = { version = "0.12.7", features = ["json"] }
rusttwald = { path = "../rusttwald/client" }
tokio = { version = "1.39.3", features = ["macros", "rt-multi-thread"] }
