[package]
name = "lowkey"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.86"
futures = "0.3.30"
reqwest = { version = "0.12.7", features = ["json"] }
rusttwald = "0.1.1"
tokio = { version = "1.39.3", features = ["macros", "rt-multi-thread"] }
