version: "3.5"
services:
  nats:
    image: nats
    ports:
      - "8222:8222"
      - "4222:4222"
    command: "--name main --jetstream --http_port 8222"

  api:
    image: lowkey
    build:
      context: .
    ports:
      - "6670:6670"
    volumes:
      - .env:/.env
