name: Build, publish and deploy backend

on:
  push:
    tags:
      - "v*"
    branches:
      - latest

jobs:
  deploy-backend:
    name: Deploy backend
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

        # Build and push

      - name: Build images
        run: docker build . -t lowkey

      - name: Push images
        run: ./scripts/push_images.sh "${{ github.ref_name }}" "${{ github.actor }}" "${{ github.token }}"

        # Deploy

      #- name: Deploy backend on kusomiso
      #  uses: appleboy/ssh-action@v1.0.3
      #  with:
      #    host: ${{ secrets.KUSOMISO_HOST }}
      #    username: ${{ secrets.KUSOMISO_USERNAME }}
      #    key: ${{ secrets.KUSOMISO_SSH_KEY }}
      #    script: ./deploy.sh
