name: Build, publish and deploy backend

on:
  push:
    tags:
      - "v*"
    branches:
      - latest

jobs:
  image:
    name: Build and Push Backend Image
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          docker build . -t "ghcr.io/cloudsftp/lowkey:latest"
          docker push "ghcr.io/cloudsftp/lowkey:latest"

  deploy:
    name: Deploy Backend
    runs-on: ubuntu-latest
    needs:
      - image

    steps:
      - name: Deploy Backend on Kusomiso
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.KUSOMISO_HOST }}
          username: ${{ secrets.KUSOMISO_USERNAME }}
          key: ${{ secrets.KUSOMISO_SSH_KEY }}
          script: ./deploy.sh
