name: Build, publish and deploy backend

on:
  push:
    branches:
      - latest

jobs:
  image:
    name: Build and Push Backend Image
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and publish
        uses: dagger/dagger-for-github@v6
        with:
          version: "latest"
          verb: call
          args: publish-image --source=. --actor=$GITHUB_ACTOR --token=env:GITHUB_TOKEN
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ github.token }}

  deploy:
    name: Deploy Backend
    runs-on: ubuntu-latest
    needs:
      - image

      - name: Deploy Backend on Kusomiso
        uses: dagger/dagger-for-github@v6
        with:
          version: "latest"
          verb: call
          args: deploy --host=env:HOST --username=env:USERNAME --key=env:KEY
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
        env:
          HOST: ${{ secrets.KUSOMISO_HOST }}
          USERNAME: ${{ secrets.KUSOMISO_USERNAME }}
          KEY: ${{ secrets.KUSOMISO_SSH_KEY }}
