name: Build, publish and deploy backend

on:
  push:
    branches:
      - latest

jobs:
  deploy:
    name: Deploy pipeline written in dagger
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup buildx
        uses: docker/setup-buildx-action@v3

      - name: Create .env
        run: |
          cp .env.example .env

      - name: Everything
        uses: dagger/dagger-for-github@v6
        with:
          version: "latest"
          verb: call
          args: pipeline --source=. --actor=$GITHUB_ACTOR --token=env:GITHUB_TOKEN --host=env:HOST --username=env:USERNAME --key=env:KEY
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ github.token }}
          HOST: ${{ secrets.KUSOMISO_HOST }}
          USERNAME: ${{ secrets.KUSOMISO_USERNAME }}
          KEY: ${{ secrets.KUSOMISO_SSH_KEY }}
