name: Build backend image

on: push

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Build
        uses: dagger/dagger-for-github@v6
        with:
          version: "latest"
          verb: call
          args: build-image --source=.
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
