name: Build and Test

on: push

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Golang with cache
        uses: magnetikonline/action-golang-cache@v5
        with:
          go-version-file: pipelines/go.mod

      - name: Check
        uses: dagger/dagger-for-github@v6
        with:
          version: "latest"
          verb: call
          args: build --source=.
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Build
        run: cargo build

      # - name: Test
      #   run: cargo test

      - name: Lint
        run: cargo clippy -- -D warnings
